sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # to append git SHA as version to docker images
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts from google cloud during dpeloyments
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # use encrypted service-accounts file
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project graceful-chain-311303
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials k8s-multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t abhi90g/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhi90g/react-test npm run test

deploy:
  provider: script # using separate script since kubernetes needs manual instrictions
  script: bash ./deploy.sh
  on:
    branch: master