apiVersion: v1
kind: PersistentVolumeClaim #
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes: # readOnlyMany, readWriteMany, ReadWriteOnce
    - ReadWriteOnce # can be used by a single node.
  resources:
    requests:
      storage: 2Gi # k8s find a storage option thats 2gb